### ISSUE TITLE
Feature 1: User can generate a workout

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/ppl-app#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can generate a workout by Push, Pull, or Legs focus. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If a user wants to perform a Push, Pull, or Legs workout, they should be able to generate a workout by that selection.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-08 at 3 53 33 PM](https://user-images.githubusercontent.com/88848572/140836665-7ce9fe7f-80bc-471d-9108-62f801602d2c.png)

<img width="625" alt="Screen Shot 2021-11-08 at 4 37 52 PM" src="https://user-images.githubusercontent.com/88848572/140840458-c6a9aeec-8819-4770-a822-8cb66be8b07b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Design the layout with CSS and HTML
- [x] Design the DOM tree in HTML so I know what it'll look like once rendered. 
- [x] Using DOM methods, fetch data for each variation (Push, Pull, Legs).
- [x] Render new list items for the intended variation. With 3 exercises for main muscle group, two for secondary, and one for tertiary. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
