### ISSUE TITLE
Feature 6: User can mark complete. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/ppl-app#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can mark an exercise complete and when the workout is complete, it will save it to their 'completed workouts', organized by date. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user clicks the check mark, the exercise will change colors to indicate that it's complete. If the user clicks the checkmark on the final exercise and all others are complete, it will save to their 'completed workouts'. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-12 at 11 28 25 AM](https://user-images.githubusercontent.com/88848572/141523977-8a0edbe8-03ba-4815-9dd6-494d69a1b4ef.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add checkmark to DOM tree and query.
- [ ] When a user clicks it, add an overlay to the li
- [ ] Change the checkmark to a doublecheck.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
