### ISSUE TITLE
Feature 8: User can view completed workouts

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/ppl-app#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

When a user taps complete, they should be able to see their completed workouts so they can repeat one they liked. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the checkmark, that exercise will be added to their 'completed workouts' tab for future reference. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-12 at 12 54 38 PM](https://user-images.githubusercontent.com/88848572/141533269-cd9101ac-df6e-408e-8a6c-ee2c1453838d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Design the completed workouts page with dummy information
- [ ] Add the 'view completed workouts' button icon to the main page
- [ ] Add a completed workouts object to my data model.
- [ ] Query the checkmark and fetch the exercise data from that exercise and add it to the completed workouts object, included the current date. 
- [ ] Create the DOM tree for the completed workouts page. 
- [ ] If the user clicks on 'view completed workouts', switch views to Completed Workouts and trigger the 'render completed workouts' function. 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
