### ISSUE TITLE
Feature 2: User can search exercises by tag

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/ppl-app#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for exercises by tag, ie "Glutes".

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If a user prefers to find an exercise by a more specific target muscle group than the broader PPL categories, they should be able to click a tag button to find relevant exercises. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="685" alt="Screen Shot 2021-11-08 at 3 58 35 PM" src="https://user-images.githubusercontent.com/88848572/140837129-18c98131-3ec5-48b6-b6e6-528c06ed2a70.png">

<img width="620" alt="Screen Shot 2021-11-08 at 4 38 00 PM" src="https://user-images.githubusercontent.com/88848572/140840503-0f451181-6b71-434f-af91-dc3ad539891b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Design tags (buttons) for users to click and search
- [x] Add data attributes to tags that match API query for muscle group
- [x] Query tags and add event listeners
- [x] Create a function to fetch data by muscle group and update the DOM 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
