### ISSUE TITLE
Feature 3: User can search for exercise by muscle group 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/ppl-app#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search exercises by target muscle group, ie “Biceps”. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user enters a value in the input and clicks search, they will see exercises that include that muscle group. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-10 at 5 10 09 PM](https://user-images.githubusercontent.com/88848572/141218905-3c8bc087-139c-433c-b586-3ffbc0eea257.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a + button below the last exercise that allows users to add one more. 
- [ ] When clicked, the user get a randomly generated exercise for that category. 
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
