### ISSUE TITLE
Feature 4: User can randomly generate a new exercise by double-clicking/tapping current exercise. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/ppl-app#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

If a user does not want to do the generated exercise, they should be able to generate a new exercise for that muscle group by clicking/tapping the exercise. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user double clicks an exercise, the exercise will be replaced by a new one with the same target muscle group. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="456" alt="Screen Shot 2021-11-08 at 4 25 55 PM" src="https://user-images.githubusercontent.com/88848572/140839361-82703966-b067-4f01-a833-68bbcf965328.png">
<img width="481" alt="Screen Shot 2021-11-08 at 4 26 15 PM" src="https://user-images.githubusercontent.com/88848572/140839374-85c26290-45f7-47fd-8728-aa6c3f45a63f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add paragraph to DOM tree for each list item indicating the user can double click for a new exercise. 
- [ ] Query the parent UL. 
- [ ] Add an event listener that identifies the UL child by node type, then find that child's ID and muscle category. 
- [ ] Fetch a new exercise that does not match the current LI's ID and remove the target LI from the DOM. 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
