### ISSUE TITLE
Feature 5: User can generate a workout by number of exercises. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/ppl-app#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

If a user wants to do more than 5 exercises, they should be able to select the number of exercises generated. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user types in the number of exercises they'd like and clicks the submit icon, they'll see that number of exercises displayed. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="653" alt="Screen Shot 2021-11-08 at 4 31 02 PM" src="https://user-images.githubusercontent.com/88848572/140840006-49421c48-23d6-41a7-bdd7-99a8ce2bb9d8.png">
<img width="902" alt="Screen Shot 2021-11-08 at 4 31 57 PM" src="https://user-images.githubusercontent.com/88848572/140840025-db2d351c-d531-41ac-9d88-e827e12d0941.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Design a new text input with a placeholder indicating the user can pick 5, 6, 7, or 8 exercises. 
- [ ] Query the input. 
- [ ] Fetch additional exercises and distribute them evenly between primary, secondary, and tertiary muscle groups. 
- [ ] The exercises will be added to the tertiary, secondary, and primary groups in that order. 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
